#!/usr/bin/env bash
#############################################################################
# Usage:
# sudo bash tor.sh
#############################################################################

set -o pipefail

LOG_FILE="/tmp/tor-proxy-install.log"
: > "$LOG_FILE"

info() { echo "==> $1"; }
ok()   { echo "OK: $1"; }
warn() { echo "WARNING: $1"; }
fail() { echo "ERROR: $1"; echo "        Details were saved to $LOG_FILE"; exit 1; }

run() { "$@" >>"$LOG_FILE" 2>&1; }

if [ "$(id -u)" -ne 0 ]; then
    echo "sudo needed, run:"
    echo "    sudo bash $0"
    exit 1
fi

if ! command -v apt-get >/dev/null 2>&1; then
    fail "This installer only supports Debian-based systems (Ubuntu, Linux Mint, Zorin OS, etc.)."
fi

REAL_USER="${SUDO_USER:-}"
if [ -z "$REAL_USER" ] || [ "$REAL_USER" = "root" ]; then
    fail "Could not determine your normal (non-root) username. Please run this script exactly as: sudo bash $0"
fi
REAL_HOME=$(eval echo "~$REAL_USER")

echo "============================================================"
echo "=============Tor Transparent Proxy - Installer=============="
echo "============================================================"
echo "This will route ALL network traffic on this computer through"
echo "the Tor network, automatically, every time you start your PC."
echo "This helps you too keep your trafic safe from ISP, bad actors,"
echo "networks administrators (eg university, work, free wifi) and"
echo "censorship."
echo "============================================================"
echo "Proudly created in Ukraine!"
echo "============================================================"
echo "If you can, please donate to Ukrainian defenders:"
echo "https://war.ukraine.ua"
echo "https://savelife.in.ua"
echo "============================================================"
echo "Glory to Ukraine! Stop the war!"
echo "============================================================"
echo "Wait 5s..."

sleep 5

echo "============================================================"
echo "Do you need bridges?"
echo "Tor bridges help you connect when Tor is blocked/censored on your"
echo "network or country, and add an extra layer against local network"
echo "observers. Installing bridge support is STRONGLY RECOMMENDED."
echo
read -rp "Install Tor bridge support now? [Y/n]: " BRIDGE_ANSWER
BRIDGE_ANSWER=${BRIDGE_ANSWER:-Y}
if [[ "$BRIDGE_ANSWER" =~ ^[Yy] ]]; then
    WANT_BRIDGES=1
else
    WANT_BRIDGES=0
    warn "Skipping bridge support. You can re-run this installer later to add it."
fi
echo

if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
    warn "The 'ufw' firewall is active and may conflict with the Tor proxy rules."
    warn "Strongly recommended to disable UFW. Tor will take care of your connection anyway..."
    read -rp "Disable ufw now so the Tor proxy works reliably? [Y/n]: " UFW_ANSWER
    UFW_ANSWER=${UFW_ANSWER:-Y}
    if [[ "$UFW_ANSWER" =~ ^[Yy] ]]; then
        run ufw disable
        ok "ufw disabled."
    else
        warn "Keeping ufw enabled - you may need to adjust its rules manually later."
    fi
fi

info "Updating package lists..."
run apt-get update || fail "Could not update package lists. Check your internet connection."
ok "Package lists updated."

info "Installing core packages (this can take a minute)..."
run apt-get install -y tor iptables zenity || fail "Failed to install core packages."
ok "Core packages installed."

if [ "$WANT_BRIDGES" -eq 1 ]; then
    info "Installing bridge support (obfs4proxy)..."
    if run apt-get install -y obfs4proxy; then
        ok "Bridge support installed."
    else
        warn "Could not install obfs4proxy. Continuing without bridge support."
        WANT_BRIDGES=0
    fi
fi

if ! id debian-tor >/dev/null 2>&1; then
    fail "The 'debian-tor' system user was not created. Tor installation may have failed."
fi

info "Configuring Tor..."

mkdir -p /etc/tor/torrc.d

if ! grep -q "^%include /etc/tor/torrc.d" /etc/tor/torrc 2>/dev/null; then
    {
        echo ""
        echo "## Added by the Tor Proxy installer"
        echo "%include /etc/tor/torrc.d"
    } >> /etc/tor/torrc
fi

cat > /etc/tor/torrc.d/50-transproxy.conf <<'EOF'
# Managed automatically by the Tor Proxy installer
VirtualAddrNetworkIPv4 10.192.0.0/10
AutomapHostsOnResolve 1
TransPort 9040
DNSPort 5353
EOF

if [ "$WANT_BRIDGES" -eq 1 ]; then
    cat > /etc/tor/torrc.d/60-bridges.conf <<'EOF'
# Managed by the "Tor Proxy Control" desktop panel.
# Do not edit this file by hand - use the desktop shortcut instead.
UseBridges 0
ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy
EOF
fi
ok "Tor configured."

info "Installing network redirection rules (this makes ALL traffic go through Tor)..."

cat > /usr/local/bin/tor-transproxy-rules.sh <<'RULES'
#!/bin/bash
# Applies firewall rules that route all outgoing traffic through Tor.
# Installed by the Tor Proxy installer.

TOR_UID=$(id -u debian-tor 2>/dev/null)
TRANS_PORT=9040
DNS_PORT=5353

[ -z "$TOR_UID" ] && exit 1

# --- IPv4 ---
iptables -F OUTPUT
iptables -t nat -F OUTPUT

# Let Tor's own traffic go out directly (avoid a routing loop)
iptables -t nat -A OUTPUT -m owner --uid-owner "$TOR_UID" -j RETURN

# Keep local/private networks working normally (LAN, localhost, etc.)
for NET in 127.0.0.0/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 169.254.0.0/16; do
    iptables -t nat -A OUTPUT -d "$NET" -j RETURN
done

# Send all DNS requests to Tor's own DNS resolver
iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports "$DNS_PORT"
iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports "$DNS_PORT"

# Send all other outgoing TCP connections through Tor
iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports "$TRANS_PORT"

# Only allow what we just redirected (or loopback / Tor itself);
# everything else is blocked so nothing can leak outside Tor.
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A OUTPUT -m owner --uid-owner "$TOR_UID" -j ACCEPT
iptables -A OUTPUT -d 127.0.0.0/8 -j ACCEPT
iptables -A OUTPUT -p tcp --dport "$TRANS_PORT" -j ACCEPT
iptables -A OUTPUT -p udp --dport "$DNS_PORT" -j ACCEPT
iptables -A OUTPUT -j DROP

# --- IPv6 (disabled entirely to prevent leaks - our transparent proxy is IPv4-only) ---
if command -v ip6tables >/dev/null 2>&1; then
    ip6tables -F OUTPUT 2>/dev/null
    ip6tables -A OUTPUT -o lo -j ACCEPT 2>/dev/null
    ip6tables -P OUTPUT DROP 2>/dev/null
fi

exit 0
RULES
chmod +x /usr/local/bin/tor-transproxy-rules.sh

cat > /etc/systemd/system/tor-transproxy.service <<'EOF'
[Unit]
Description=Tor transparent proxy firewall rules
After=network-online.target tor.service
Wants=network-online.target
Requires=tor.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/bin/tor-transproxy-rules.sh
ExecStop=-/usr/sbin/iptables -F OUTPUT
ExecStop=-/usr/sbin/iptables -t nat -F OUTPUT
ExecStop=-/usr/sbin/ip6tables -P OUTPUT ACCEPT

[Install]
WantedBy=multi-user.target
EOF

ok "Firewall rules installed."

info "Enabling and applying..."
run systemctl daemon-reload
run systemctl enable tor
run systemctl enable tor-transproxy.service
run systemctl restart tor
sleep 2
run systemctl restart tor-transproxy.service
ok "DONE!"

info "Creating the Tor Proxy Control panel..."

cat > /usr/local/bin/tor-proxy-control.sh <<'CONTROL_EOF'
#!/bin/bash
# Tor Proxy Control Panel (zenity GUI)
# Launched from the "Tor Proxy Control" Desktop shortcut.

BRIDGE_CONF="/etc/tor/torrc.d/60-bridges.conf"
export DISPLAY="${DISPLAY:-:0}"

have_bridges() { [ -f "$BRIDGE_CONF" ]; }

ask_password_and_run() {
    # $1 = description shown on failure, remaining args = command to run as root
    local desc="$1"; shift
    local pass
    pass=$(zenity --password --title="Tor Proxy - Password required" 2>/dev/null)
    if [ -z "$pass" ]; then
        zenity --error --text="Cancelled: no password entered." 2>/dev/null
        return 1
    fi
    printf '%s\n' "$pass" | sudo -S -p '' "$@" >/tmp/tor-proxy-control.log 2>&1
    local status=$?
    pass=""
    if [ $status -ne 0 ]; then
        zenity --error --text="$desc failed. See /tmp/tor-proxy-control.log for details." 2>/dev/null
    fi
    return $status
}

set_bridge_mode() {
    local mode="$1"
    if [ "$mode" -eq 1 ] && ! grep -q '^Bridge ' "$BRIDGE_CONF" 2>/dev/null; then
        zenity --warning --title="Tor Proxy" \
            --text="You haven't entered any bridges yet.\nUse 'Enter / update my Tor bridges' first." 2>/dev/null
        return
    fi
    ask_password_and_run "Switching mode" bash -c \
        "sed -i 's/^UseBridges .*/UseBridges $mode/' '$BRIDGE_CONF' && systemctl restart tor"
    if [ $? -eq 0 ]; then
        zenity --info --title="Tor Proxy" --text="Done. Tor has been restarted with the new setting." 2>/dev/null
    fi
}

edit_bridges() {
    local tmp tmp_new tmp_final
    tmp=$(mktemp)
    tmp_new=$(mktemp)
    tmp_final=$(mktemp)

    grep '^Bridge ' "$BRIDGE_CONF" 2>/dev/null | sed 's/^Bridge //' > "$tmp"

    zenity --text-info --editable \
        --title="Paste your Tor bridges below (one per line), then click OK" \
        --width=650 --height=400 --filename="$tmp" > "$tmp_new"
    if [ $? -ne 0 ]; then
        rm -f "$tmp" "$tmp_new" "$tmp_final"
        return
    fi

    {
        echo "# Managed by the \"Tor Proxy Control\" desktop panel."
        echo "# Do not edit this file by hand - use the desktop shortcut instead."
        grep '^UseBridges' "$BRIDGE_CONF" 2>/dev/null || echo "UseBridges 0"
        echo "ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy"
        while IFS= read -r line; do
            [ -z "$line" ] && continue
            if [[ "$line" =~ ^[Bb]ridge[[:space:]] ]]; then
                echo "$line"
            else
                echo "Bridge $line"
            fi
        done < "$tmp_new"
    } > "$tmp_final"

    ask_password_and_run "Saving bridges" bash -c \
        "cp '$tmp_final' '$BRIDGE_CONF' && systemctl restart tor"
    if [ $? -eq 0 ]; then
        zenity --info --title="Tor Proxy" --text="Bridges saved and Tor restarted." 2>/dev/null
    fi

    rm -f "$tmp" "$tmp_new" "$tmp_final"
}

show_status() {
    local svc bridging
    if systemctl is-active --quiet tor; then svc="Tor service: ACTIVE"; else svc="Tor service: INACTIVE"; fi
    if have_bridges; then
        if grep -q '^UseBridges 1' "$BRIDGE_CONF" 2>/dev/null; then
            bridging="Mode: BRIDGES"
        else
            bridging="Mode: DIRECT (no bridges)"
        fi
    else
        bridging="Bridge support: not installed"
    fi
    zenity --info --title="Tor Proxy Status" --text="$svc\n$bridging" 2>/dev/null
}

while true; do
    STATUS_LINE="$(systemctl is-active --quiet tor && echo 'Tor: ACTIVE' || echo 'Tor: INACTIVE')"
    if have_bridges; then
        CHOICE=$(zenity --list --title="Tor Proxy Control Panel" \
            --text="$STATUS_LINE" --column="Action" --height=380 --width=480 \
            "Switch to DIRECT connection (no bridges)" \
            "Switch to BRIDGE connection" \
            "Enter / update my Tor bridges" \
            "Show status" \
            "Exit" 2>/dev/null)
    else
        CHOICE=$(zenity --list --title="Tor Proxy Control Panel" \
            --text="$STATUS_LINE\nBridge support was not installed." \
            --column="Action" --height=250 --width=480 \
            "Show status" \
            "Exit" 2>/dev/null)
    fi

    case "$CHOICE" in
        "Switch to DIRECT connection (no bridges)") set_bridge_mode 0 ;;
        "Switch to BRIDGE connection") set_bridge_mode 1 ;;
        "Enter / update my Tor bridges") edit_bridges ;;
        "Show status") show_status ;;
        *) exit 0 ;;
    esac
done
CONTROL_EOF
chmod +x /usr/local/bin/tor-proxy-control.sh
ok "Control panel installed."

info "Creating the Desktop shortcut..."
mkdir -p "$REAL_HOME/Desktop"
DESKTOP_FILE="$REAL_HOME/Desktop/TorProxyControl.desktop"
cat > "$DESKTOP_FILE" <<'EOF'
[Desktop Entry]
Type=Application
Name=Tor Proxy Control
Comment=Manage your Tor transparent proxy (bridges, direct connection)
Exec=/usr/local/bin/tor-proxy-control.sh
Icon=security-high
Terminal=false
Categories=Network;Security;
EOF
chmod +x "$DESKTOP_FILE"
chown "$REAL_USER":"$REAL_USER" "$DESKTOP_FILE"
run sudo -u "$REAL_USER" gio set "$DESKTOP_FILE" metadata::trusted true
ok "Desktop shortcut created."

info "Verifying Tor is running..."
sleep 2
if systemctl is-active --quiet tor; then
    ok "Tor is active."
else
    warn "Tor is not active yet. This can sometimes take a bit longer right after install."
    warn "Check later with: systemctl status tor"
fi

echo
echo "============================================================"
echo " Installation complete!"
echo "============================================================"
echo "- All system traffic is now routed through Tor, automatically,"
echo "  including after every reboot."
echo "- A 'Tor Proxy Control' shortcut was added to your Desktop -"
echo "  use it any time to switch between direct/bridge mode or to"
echo "  enter your own bridges (no need to touch any config file)."
echo "- You can verify your connection at https://check.torproject.org"
echo
if [ "$WANT_BRIDGES" -eq 0 ]; then
    echo "NOTE: bridge support was not installed. If Tor is blocked on"
    echo "      your network later, re-run this installer and choose 'y'."
    echo
fi
echo "Note: you can get bridges from https://check.torproject.org or"
echo "by sending /start than /obfs4 to @GetBridgesBot in Telegram or"
echo "by sending email (Gmail adresses only!) to bridges@torproject.org"
echo

echo "============================================================"
echo "Thank you for using my scripts!"
echo "============================================================"
echo "Sorry, that i ask multipletimes,  but... This is really important..."
echo "If you can, please donate to Ukrainian defenders:"
echo "https://war.ukraine.ua"
echo "https://savelife.in.ua"
echo "============================================================"
echo "Glory to Ukraine! Stop the war!"
echo "============================================================"
echo "Wait 5s..."

sleep 5

SELF_PATH="$(readlink -f "$0" 2>/dev/null)"
if [ -n "$SELF_PATH" ] && [ -f "$SELF_PATH" ]; then
    echo "Removing installer file to save space..."
    rm -f -- "$SELF_PATH"
fi

exit 0